<#
    .DESCRIPTION
        Embed one or more CMS-encrypted password files as base64 into an Intune Remediation script template
        by replacing the marked block:

            # <Payload>
            # ... anything ...
            # </Payload>

        with a generated $IntunePayload hashtable. The CMS files stay encrypted (admin must deploy the
        matching certificate's private key to Cert:\LocalMachine\My on each device). The template is read as-is and only the
        marked block is rewritten so the rest of the remediation script is untouched.

    .PARAMETER VersionFiles
        Hashtable mapping integer version number to CMS file path. Use this form when the version numbers
        do not line up with positional 1, 2, 3 numbering - a window that has rolled forward (e.g. versions
        3, 4, 5) or one with gaps (e.g. 3, 5, 6). Cannot be combined with -CmsFile.

    .PARAMETER CmsFile
        Array of CMS file paths in version order. Version numbers are assigned positionally starting at 1.
        Cannot be combined with -VersionFiles.

    .PARAMETER CertThumbprint
        SHA-1 thumbprint (40 hex characters) of the certificate that was used to encrypt the CMS files.
        Embedded in the payload so the remediation script can resolve the matching certificate at runtime.

    .PARAMETER TemplateFile
        Path to the remediation script template. Must contain a "# <Payload>" / "# </Payload>" marker block.

    .PARAMETER OutputFile
        Path where the generated remediation script will be written. Parent directories are created if missing.

    .PARAMETER Force
        Overwrite OutputFile if it already exists.

    .EXAMPLE
        Build-IntunePayload.ps1 -CmsFile 'C:\BiosPw\pw-v1.cms','C:\BiosPw\pw-v2.cms' -CertThumbprint 'A1B2C3D4E5F60718293A4B5C6D7E8F90A1B2C3D4' -TemplateFile '.\Manage-DellBiosPasswords-WMI-Remediate.template.ps1' -OutputFile '.\out\Manage-DellBiosPasswords-WMI-Remediate.ps1'

        Build-IntunePayload.ps1 -VersionFiles @{ 3='pw-v3.cms'; 4='pw-v4.cms'; 5='pw-v5.cms' } -CertThumbprint 'A1B2C3D4E5F60718293A4B5C6D7E8F90A1B2C3D4' -TemplateFile '.\Template.ps1' -OutputFile '.\Out.ps1' -Force

    .NOTES
        Created by: Jon Anderson
        Version: 1.0.0
        Modified: 2026-06-06
#>

#Parameters ===================================================================================================================

[CmdletBinding(PositionalBinding = $false, DefaultParameterSetName = 'Positional')]
param(
    [Parameter(Mandatory = $true, ParameterSetName = 'Hashtable')]
    [ValidateNotNullOrEmpty()]
    [hashtable]$VersionFiles,

    [Parameter(Mandatory = $true, ParameterSetName = 'Positional')]
    [ValidateNotNullOrEmpty()]
    [string[]]$CmsFile,

    [Parameter(Mandatory = $true)]
    [ValidateNotNullOrEmpty()]
    [ValidatePattern('^[0-9A-Fa-f]{40}$')]
    [string]$CertThumbprint,

    [Parameter(Mandatory = $true)]
    [ValidateScript({
            if (-not (Test-Path -LiteralPath $_ -PathType Leaf))
            {
                throw "TemplateFile not found: $_"
            }
            return $true
        })]
    [string]$TemplateFile,

    [Parameter(Mandatory = $true)]
    [ValidateNotNullOrEmpty()]
    [string]$OutputFile,

    [Parameter(Mandatory = $false)]
    [switch]$Force
)

#Script version
$Version = '1.0.0'

#Functions ====================================================================================================================

function Convert-CmsFileToBase64
{
    #Read a CMS file as bytes and return its base64-encoded string

    param(
        [Parameter(Mandatory = $true)][ValidateNotNullOrEmpty()][string]$Path
    )
    if (-not (Test-Path -LiteralPath $Path -PathType Leaf))
    {
        throw "CMS file not found: $Path"
    }
    $Resolved = (Resolve-Path -LiteralPath $Path).Path
    $Bytes = [System.IO.File]::ReadAllBytes($Resolved)
    return [Convert]::ToBase64String($Bytes)
}

function Format-PayloadBlock
{
    #Build the generated payload hashtable, sandwiched between the <Payload>/</Payload> markers

    param(
        [Parameter(Mandatory = $true)][ValidateNotNullOrEmpty()][string]$CertThumbprint,
        [Parameter(Mandatory = $true)][ValidateNotNullOrEmpty()][System.Collections.IDictionary]$Files
    )
    $Builder = [System.Text.StringBuilder]::new()
    [void]$Builder.AppendLine("# <Payload>")
    [void]$Builder.AppendLine("# Generated by Build-IntunePayload.ps1 on $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss zzz'). Do not hand-edit.")
    [void]$Builder.AppendLine("`$IntunePayload = @{")
    [void]$Builder.AppendLine("    CertThumbprint = '$CertThumbprint'")
    [void]$Builder.AppendLine("    Files = [ordered]@{")
    foreach ($Key in ($Files.Keys | Sort-Object { [int]$_ }))
    {
        [void]$Builder.AppendLine("        '$Key' = '$($Files[$Key])'")
    }
    [void]$Builder.AppendLine("    }")
    [void]$Builder.AppendLine("}")
    [void]$Builder.Append("# </Payload>")
    return $Builder.ToString()
}

function Update-TemplatePayload
{
    #Replace the <Payload>...</Payload> block in the template content with a new payload block

    param(
        [Parameter(Mandatory = $true)][ValidateNotNull()][string]$TemplateContent,
        [Parameter(Mandatory = $true)][ValidateNotNull()][string]$PayloadBlock
    )
    $Pattern = '(?ms)^[ \t]*#\s*<Payload>.*?^[ \t]*#\s*</Payload>'
    $Regex = [regex]::new($Pattern)
    $Match = $Regex.Match($TemplateContent)
    if (-not $Match.Success)
    {
        throw "Template does not contain a '# <Payload> ... # </Payload>' block."
    }
    #Splice via Substring so the generated block (which contains literal '$', e.g. $IntunePayload)
    #is treated literally, avoiding the $-substitution that Regex.Replace's string-overload would apply
    return $TemplateContent.Substring(0, $Match.Index) + $PayloadBlock + $TemplateContent.Substring($Match.Index + $Match.Length)
}

#Main =========================================================================================================================

Write-Output "Build-IntunePayload.ps1 v$Version"

#Resolve template/output paths through the PowerShell provider so relative paths honor the shell's
#current location ($PWD) rather than .NET's process current directory ([Environment]::CurrentDirectory),
#which does not track Set-Location. TemplateFile must exist; OutputFile may not, so resolve it unresolved.
$TemplatePath = (Resolve-Path -LiteralPath $TemplateFile).Path
$OutputPath = $PSCmdlet.GetUnresolvedProviderPathFromPSPath($OutputFile)

#Normalize the (version -> file path) map regardless of which parameter set was used.
#Keys are stored as strings so the OrderedDictionary indexer never treats them as positions.
$FileMap = [ordered]@{}
if ($PSCmdlet.ParameterSetName -eq 'Hashtable')
{
    foreach ($Key in ($VersionFiles.Keys | Sort-Object { [int]$_ }))
    {
        $FileMap["$Key"] = $VersionFiles[$Key]
    }
}
else
{
    for ($i = 0; $i -lt $CmsFile.Count; $i++)
    {
        $FileMap["$($i + 1)"] = $CmsFile[$i]
    }
}

if ($FileMap.Count -eq 0)
{
    throw "At least one CMS file must be specified."
}

#Validate each version key is a positive integer and the file exists
foreach ($Key in $FileMap.Keys)
{
    $IntKey = 0
    if (-not [int]::TryParse("$Key", [ref]$IntKey) -or $IntKey -le 0)
    {
        throw "Version key must be a positive integer. Got: '$Key'"
    }
    $Path = $FileMap[$Key]
    if (-not (Test-Path -LiteralPath $Path -PathType Leaf))
    {
        throw "CMS file for version $Key not found: $Path"
    }
}

#Validate the output file does not exist (unless -Force)
if ((Test-Path -LiteralPath $OutputPath) -and -not $Force)
{
    throw "OutputFile already exists: $OutputPath. Use -Force to overwrite."
}

Write-Output "Template:    $TemplatePath"
Write-Output "Output:      $OutputPath"
Write-Output "Cert SHA-1:  $CertThumbprint"
Write-Output "Versions:    $($FileMap.Keys -join ', ')"
Write-Output ""
Write-Output "Encoding CMS files..."

#Encode each CMS file in version order
$Encoded = [ordered]@{}
foreach ($Key in $FileMap.Keys)
{
    $Path = $FileMap[$Key]
    $Base64 = Convert-CmsFileToBase64 -Path $Path
    $Encoded["$Key"] = $Base64
    $SrcKb = [math]::Round((Get-Item -LiteralPath $Path).Length / 1024, 2)
    $B64Kb = [math]::Round($Base64.Length / 1024, 2)
    Write-Output ("  v{0,-3}  {1,7:N2} KB -> {2,7:N2} KB base64  {3}" -f $Key, $SrcKb, $B64Kb, $Path)
}

#Build the payload block and splice it into the template
$PayloadBlock = Format-PayloadBlock -CertThumbprint $CertThumbprint -Files $Encoded
$TemplateContent = Get-Content -LiteralPath $TemplatePath -Raw
$Updated = Update-TemplatePayload -TemplateContent $TemplateContent -PayloadBlock $PayloadBlock

#Ensure output directory exists. -LiteralPath defaults to returning the parent; -Parent is incompatible
#with -LiteralPath (they live in different parameter sets), so do not specify it explicitly.
$OutputDir = Split-Path -LiteralPath $OutputPath
if ($OutputDir -and -not (Test-Path -LiteralPath $OutputDir))
{
    try
    {
        New-Item -ItemType Directory -Path $OutputDir -Force -ErrorAction Stop | Out-Null
    }
    catch
    {
        throw "Failed to create output directory: $OutputDir. $($_.Exception.Message)"
    }
}

#Write UTF-8 without BOM
$Utf8NoBom = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText($OutputPath, $Updated, $Utf8NoBom)

$OutSize = (Get-Item -LiteralPath $OutputPath).Length
$OutSizeKb = [math]::Round($OutSize / 1024, 2)
Write-Output ""
Write-Output "Wrote $OutSizeKb KB to $OutputPath"

#Soft warning about Intune's per-script size cap (~200 KB at the time of writing)
if ($OutSize -gt 200KB)
{
    Write-Warning "Output script is over 200 KB. Intune Remediation scripts have a size cap (~200 KB at the time of writing). Verify before assigning."
}
